name: data_engineering_pipelines
version: "1.0.0"
config-version: 2

profile: data_engineering_pipelines

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  # Global defaults for ALL models unless overridden below
  +database: bidb
  +schema: dbt_datasets
  +materialized: view   # safe default; override per folder/file as needed

  data_engineering_pipelines:
    raw:
      +materialized: table     # or 'table' if you prefer
    staging:
      +materialized: view
    marts:
      +materialized: table