# dbt_project.yml (minimal, clean)
name: data_engineering_pipelines
version: "1.0.0"
config-version: 2
profile: data_engineering_pipelines

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]

models:
  +database: bidb
  # DO NOT set +schema here → lets the job's Schema (dbt Cloud env) be used as-is
  +materialized: view

  data_engineering_pipelines:
    raw:
      +materialized: table