sources:
  - name: src
    database: bidb
    schema: dl_bi
    quoting:
      identifier: true
    tables:
      - name: "user"
        description: "Raw user data from Salesforce"
      - name: "account"
        description: "Raw account data from Salesforce"
        
      - name: "appointment"
        description: "Raw appointment data from Salesforce"
      - name: "contract"
        description: "Raw contract data from Salesforce"  
      - name: "new_product2_mapping"
        description: "Raw new product2 mapping data from Salesforce"
      - name: "opportunity"
        description: "Raw opportunity data from Salesforce"
      - name: "product2"
        description: "Raw product2 data from Salesforce"
      - name: "sbqq__quote__c"  
      - name: "SBQQ__QuoteLine__c"
      - name: "userrole"
      - name: "opportunitylineitem"
      - name: "sbqq__subscription__c"
      - name: "historypdms"
      - name: "HistoryHCM"
      - name: "at_risk_product__c_hcm"
      - name: "customer_engagement__c_hcm"