sources:
  - name: src
    database: bidb
    schema: dl_bi
    quoting:
      identifier: true
    tables:
      - name: "user"
      - name: "account"
      - name: "appointment"
      - name: "contract"
      - name: "new_product2_mapping"
      - name: "opportunity"
      - name: "product2"
      - name: "sbqq__quote__c"
      - name: "quoteline"
      - name: "userrole"
      - name: "opportunitylineitem"
      - name: "sbqq__subscription__c"